- hosts: localhost
  vars:
    pip_install_packages:
      - name: 
        - awscli
        - j2cli
        - ansible-lint
        - yapf
        - pycodestyle 
        - tldr
  pre_tasks:
    - name: Install dependencies
      become: true
      package:
        name: 
        - git
        - shellcheck
        - zsh
        - fzf
        state: present

  roles:
    - role: geerlingguy.docker
      docker_install_compose: true

    - role: gantsign.antigen
      users:
        - username: '{{ ansible_env.USER }}'
          antigen_libraries:
            - name: oh-my-zsh
          antigen_theme:
            name: blinks
          antigen_bundles:
            - name: git
            - name: pip
            - name: command-not-found
            - name: zsh-syntax-highlighting
              url: zsh-users/zsh-syntax-highlighting
            - name: zsh-autosuggestions
              url: zsh-users/zsh-autosuggestions
            - name: zsh-completions
              url: zsh-users/zsh-completions

    - role: gantsign.visual-studio-code
      users:
        - username: '{{ ansible_env.USER }}'
          visual_studio_code_extensions:
            - alphabotsec.vscode-eclipse-keybindings
            - vscoss.vscode-ansible
            - ms-python.python
            - wholroyd.jinja
            - timonwong.shellcheck
            - mauve.terraform
            - mads-hartmann.bash-ide-vscode

    - role: geerlingguy.pip
      pip_executable: pip3