- hosts: localhost
  vars:
    pip_install_packages:
      - name: 
        - awscli
        - j2cli
        - ansible-lint
        - yapf
        - pycodestyle 
        - tldr
        - ansible
        - tmuxp
  pre_tasks:
    - name: Install dependencies
      become: true
      package:
        name: 
        - git
        - shellcheck
        - zsh
        - fzf
        - jq
        - htop
        state: present

  roles:
    - role: geerlingguy.docker
      docker_install_compose: true

    - role: gantsign.visual-studio-code
      users:
        - username: '{{ ansible_env.USER }}'
          visual_studio_code_extensions:
            - Cardinal90.multi-cursor-case-preserve
            - dracula-theme.theme-dracula
            - Tim-Koehler.helm-intellisense
            - eamodio.gitlens
            - hashicorp.terraform
            - ms-azuretools.vscode-docker
            - ms-python.python
            - ms-python.vscode-pylance
            - ms-toolsai.jupyter
            - ms-toolsai.jupyter-keymap
            - ms-toolsai.jupyter-renderers
            - redhat.vscode-commons
            - redhat.vscode-yaml
            - samuelcolvin.jinjahtml
            - timonwong.shellcheck
            - vscodevim.vim

    - role: geerlingguy.pip
      pip_executable: pip3
